FROM node:22.12.0

WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install

# Copy all the backend files
COPY . .

EXPOSE 5000

# Command to run your application
CMD ["npm", "start"]
